v1.0.0

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -1,4 +1,4 @@
-name: B3 trading signals bot
+name: Market forecaster bot
 
 on:
   schedule:
@@ -28,7 +28,7 @@ jobs:
         run: |
           for i in {1..3}; do
           echo "Attempt $i of 3."
-            python b3_trading_signals_bot.py && break || echo "Attempt $i has failed. Retrying in 30 seconds." && sleep 30
+            python market_forecaster_bot.py && break || echo "Attempt $i has failed. Retrying in 30 seconds." && sleep 30
           done
 
       - name: Upload report
